### ISSUE TITLE
a `version` flag?

### ISSUE THREAD

**Issue by deogracia** [erri120/rpgmpacker#40]
Hi,

Is there a way you can add a `version` flag or output the version number the command is ? I'm not sure of how much work it'll be to do it and the complexity added to your current workflow.

As far as I can see, there's no mention either in the `--help` nor a flag.

**Comment by erri120** [comment]
There is no version info at all in the program because the only times you have a version is in the release workflow through dispatch arguments.
I could maybe define the version as compiler constant and change it via a cmake flag or something but I'll have to test that first.
Do you require the version info somewhere or is this just because "why not"?

**Comment by deogracia** [comment]
I don't really require it. It's part of "it would be 'cool'" and "maybe it could help me be sure that I'm packaging the right version" :P 

I think I could totally live without it.  I don't want you to add something you don't need or that would add more work that it should.

Thanks for thinking about it :D

**Comment by deogracia** [comment]
Thanks :D 

````
